// export const backend = 'https://stage-api.publiq.network';
export const backend = 'http://192.168.10.104:8001';
export const dsBackend = 'https://stage-ds.publiq.network';
export const daemonAddressFirst = 'wss://south.publiq.network:443/websocket_stage';
export const daemonAddressSecond = 'wss://south.publiq.network:8092/websocket_stage';
export const currentVersion = 'presentation';
export const explorerAddress = 'https://explorer.publiq.network';
export const daemonHttpsAddress = 'https://south.publiq.network:443/api_stage';
export const GA_ID = 'NUA-99830524-3';
export const froalaEditorKey = '1D4I4C10B6eF5C4C3E3E2C2A5D6A3A1xusedc1D-17C6F-11dzj==';
export const filestorageLink = 'https://stage-file.publiq.network';
export const mainSiteUrl = 'https://stage.publiq.site';
